### PR TITLE
Enhanced Error Handling and Testing Across Python Modules

### PR DESCRIPTION
**Pull request by Cre4T3Tiv3**
This pull request introduces robust error handling and comprehensive testing to all in-scope Python modules. The key changes include:

- Addition of error handling mechanisms to catch and appropriately respond to potential exceptions.
- Implementation of unit tests to ensure the functionality of each module and to maintain the integrity of the overall application.
- Improved reliability and stability of the application by catching potential issues early in the development cycle.
- These enhancements aim to improve the overall quality of the code, making it more robust, reliable, and maintainable.

### CODE REVIEW

**Review by EtherByteExplorer — APPROVED** [review]
Self-approved as the repository owner.

**Review by EtherByteExplorer — APPROVED** [review]
Self-approved as the repository owner.

**Review by EtherByteExplorer — APPROVED** [review]
Self-approved as the repository owner.

**Review by EtherByteExplorer — APPROVED** [review]
Self-approved as the repository owner.

**Review by EtherByteExplorer — APPROVED** [review]
Self-approved as the repository owner.

**Review by EtherByteExplorer — APPROVED** [review]

**Comment by Cre4T3Tiv3** [comment]
Self-approved as the repository owner.

**Pull request closed without merging**
